# Site settings
title: Friends of Burma, Inc.
email: admin@lwinmoe.org
description: > # this means to ignore newlines until "baseurl:"
   Friends of Burma is dedicated to helping the Christians of Burma in whatever way they want to be helped.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://friendsofburma.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

include: ['_pages']
